name: Contractor Onboarding
description: Template for onboarding new contractors
title: "[Contractor Name] - Onboarding Request"
labels: ["contractor-onboarding"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🔔 **IMPORTANT: Before Opening an on-boarding issue, please be sure you have reviewed new requirements under the [Contractor Services Program](https://thehub.github.com/guides/procurement/contractor-services-program/)** 🔔 

        1. If you are here, you have identified a specific contractor, have received the total estimated spend for the duration of the scheduled contractor's work, and have opened a Purchase Order in Procureweb for the estimated amount. If this is not the case, please get in touch with your Agency/Vendor for a quote in order to fulfill the PO Process. If you are looking to grant a Microsoft employee access to GitHub systems, please go [here](https://github.com/github/Dual-Access/issues/new?assignees=&labels=&template=dual-access---msft-collaborator.md&title=%5BInsert+Name%5D+%2F+%5BInsert+Handle%5D) to complete a Dual Access issue.
        2. All Contractors must complete a HireRight background check which can take anywhere from **_2 days to 4 weeks to clear_** depending on their location and background. Please take this into consideration when making your request.
        3. If your Contractor requires access to Microsoft corporate resources, please open a [Zendesk ticket](https://github-hr.zendesk.com/hc/en-us/requests/new?ticket_form_id=360000790411) for People Systems and include a link to this ticket.
        4. We cannot move forward with your request until **_ALL the appropriate fields below have been completed._**
        5. Please allow 48 hours for Procurement to respond to your request. HR will need an **_additional 3-5 days_** after Procurement approval to on-board the contractor

        ---
        ### CONTRACTOR INFORMATION (Hiring Manager to fill out):

  - type: input
    id: po_link
    attributes:
      label: "1. Link to Microsoft PO (when applicable):"
    validations:
      required: false

  - type: textarea
    id: sow
    attributes:
      label: "2. Statement of Work (SOW) / Work Order:"
      description: "(attach a .doc for individual contractor or .pdf of signed SOW if contractor is working on a project)"
    validations:
      required: true

  - type: input
    id: agency_name
    attributes:
      label: "3. Preferred Agency/Vendor name:"
    validations:
      required: true

  - type: input
    id: agency_email
    attributes:
      label: "4. Preferred Agency/Vendor email address:"
    validations:
      required: true

  - type: input
    id: signatory_name
    attributes:
      label: "5. Preferred Agency/Vendor signatory name (needed only for agencies other than TargetCW and eXcell):"
    validations:
      required: false

  - type: input
    id: signatory_email
    attributes:
      label: "6. Preferred Agency/Vendor signatory email (needed only for agencies other than TargetCW and eXcell):"
    validations:
      required: false

  - type: input
    id: business_sponsor
    attributes:
      label: "7. Name of GitHub Business Sponsor:"
    validations:
      required: true

  - type: input
    id: contractor_name
    attributes:
      label: "8. Contractor's full legal name (and Preferred Name, if applicable):"
    validations:
      required: true

  - type: input
    id: contractor_email
    attributes:
      label: "9. Contractor's email address (This address must be registered and verified at github.com/settings/emails for the account provided in Question 20 below. This is to confirm the GitHub handle belongs to the contractor. Onboarding WILL NOT proceed until completed.):"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "10. Title: _[other than contractor]_"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "11. Contractors location (Country/State-Province/City) - _No_ category of GitHub worker (FTE's, contractors, MS workers, or others) should be onboarded/provided access to GitHub internal systems if they are based in any of the following countries listed [here](https://github.com/github/Workplace-Security/blob/master/Safety-and-Security-Playbook/Travel-Security-and-Protective-Services/travel-security-country-list.md):"
    validations:
      required: true

  - type: checkboxes
    id: employment_type
    attributes:
      label: "12. Part Time or Full Time:"
      options:
        - label: "Part Time"
        - label: "Full Time"
    validations:
      required: true

  - type: input
    id: weekly_hours
    attributes:
      label: "13. Estimated hours expected to work weekly:"
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: "14. Start Date (mm/dd/yyyy):"
    validations:
      required: true

  - type: input
    id: end_date
    attributes:
      label: "15. End Date (mm/dd/yyyy):"
    validations:
      required: true

  - type: input
    id: github_handle
    attributes:
      label: "16. GitHub Handle: Handle will be used to enter Contractor into WorkDay and access will be provisioned based on their handle. Note: In accordance with MSFT and FedRAMP policies, their handle MUST begin with \"v-\"."
    validations:
      required: true

  - type: input
    id: microsoft_alias
    attributes:
      label: "17. Microsoft Alias (if applicable):"
      description: "_[If this person works at MSFT, please provide their alias.]_"
    validations:
      required: false

  - type: checkboxes
    id: handle_registered
    attributes:
      label: "18. HM Confirms contractor has registered a username, owns this handle, and verified it belongs to them on https://github.com/:"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: email_associated
    attributes:
      label: "19. HM confirms contractor's personal email is associated with their GitHub Handle:"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: supervisory_org
    attributes:
      label: "20. Do you have a Supervisory Org? (You must have a Supervisory org in Workday in order to approve hours. If you have direct reports, you most likely have one. If not, one will need to be created.):"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: textarea
    id: background_check
    attributes:
      label: "21. A Microsoft Compliant HireRight Background Check will need to be provided. (If the agency/supplier is not already registered in Microsoft's Supplier Screening Program, MSFT would need to order the self-pay screen for the contractor if this onboarding is urgent. Otherwise, the agency/supplier can 1) request a self-pay screen for the contractor to be onboarded into MSFT systems and/or 2) start their registration process for Microsoft's Supplier Screening Program by contacting one of the following support aliases: Americas - supscrn@microsoft.com or EMEA and APAC - esscrng@microsoft.com). Please provide the Hire Right Request Number and PDF of background check"
    validations:
      required: true

  - type: input
    id: training_date
    attributes:
      label: "22. Please note your supplier WILL need to ensure the contractor has [completed GitHub Security and Privacy Awareness Training](https://thehub.github.com/news/2024-05-23-contractor-training-awareness/). Please provide the supplier with this externally accessible [attestation form](https://docs.google.com/forms/d/e/1FAIpQLSfMUsX3TrBlIuaxRHXiDejf6yvWxbouCzlSqVTKzAgfgRsPXg/viewform) which has the links to the training and must be completed by the contractor. Once you've received confirmation from the supplier that the contractor has completed training, add the completion date to show this requirement is complete. This date will be verified against the attestation form."
      placeholder: "xx/xx/xx"
    validations:
      required: true

  - type: checkboxes
    id: internal_access
    attributes:
      label: "24. Will your contractor need access to any internal Github Resources (The Hub, repositories, or issues):"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: textarea
    id: entitlements
    attributes:
      label: "25. If you answered \"yes\" to question 25, please add the contractor's handle to the following entitlement file:"
      description: "https://github.com/github/entitlements/blob/master/github.com/github/org/always-on/member.txt"
    validations:
      required: false

  - type: checkboxes
    id: okta_access
    attributes:
      label: "26. If your contractor requires Okta access for GitHub systems (ex. Slack, Google Mail, repos, Hub, Power BI, etc), they will need to be shipped a GitHub-managed device. If this is the case, please submit a ticket to IT with the contractors name, shipping address, and contact number here: https://github-it.zendesk.com/hc/en-us/requests/new"
      description: "_Note: If you do not provide them with a GitHub-managed device, they will not receive Okta access. The only exception to this is if they have a MSFT-issued device or a MSFT OS image._"
      options:
        - label: "Submit ticket"
    validations:
      required: false

  - type: checkboxes
    id: role_type
    attributes:
      label: "27. Is the contactor in an Engineering Role?:"
      options:
        - label: "Engineering Role"
        - label: "Non Engineering Role"
    validations:
      required: true

  - type: checkboxes
    id: microsoft_access
    attributes:
      label: "28. Will the contractor need access to Microsoft systems and tools? :"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: textarea
    id: microsoft_tools
    attributes:
      label: "29. If you answered \"yes\" to question 29, please confirm which tools"
    validations:
      required: false

  - type: textarea
    id: business_justification
    attributes:
      label: "30. Please provide a business justification for why they will need Microsoft systems and tools?"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        #### 🔔**Business Sponsor ACTION Item:** Row 22 - Required Training
        The GitHub Business Sponsor is required to ensure the contractor has [completed GitHub Security and Privacy Awareness Training](https://thehub.github.com/news/2024-05-23-contractor-training-awareness/). As the business sponsor, you must provide the supplier with this externally accessible [attestation form](https://docs.google.com/forms/d/e/1FAIpQLSfMUsX3TrBlIuaxRHXiDejf6yvWxbouCzlSqVTKzAgfgRsPXg/viewform) which has the links to the training and must be completed by the contractor. The completion of this form will be validated by HR before the contractor can be onboarded in Workday.

        ---
        #### 🔔**PROCUREMENT ACTION ITEM:** After SOW or Work Order is signed, Procurement to add Label: **Ready for HR Ops** 🔔

        ---

        ### HR Ops: @github/github-hr-ops
        | | |
        | ---------------------------------- | ---------------------------------- |
        | __Enter Contractor into WorkDay after background check clears AND training verification complete?__|  <ul><li>- [ ] Yes</li>
        ---
        #### 🔔**HR OPS ACTION ITEM:** After HR Ops enters Contractor into Workday, HR Ops to add Label: **Ready for IT** 🔔
        ---
        ### IT: @github/it 
        | | |
        | ---------------------------------- | ---------------------------------- |
        | __GitHub apps:__ Hiring manager can add apps for their contractors by following the instructions [here:](https://thehub.github.com/it/guides/contractor-onboarding/) | 
        | __Slack channels:__ Please create an IT Zendesk ticket with the Slack channels needed|
        | __Machine:__ IT will allocate the proper machine based on the response to question 28|
          
         🔔**CONTRACTOR ACCOUNT ACCESS PDF:** Please make sure to provide your contractor this pdf with instructions on how to access their GitHub and Okta accounts:🔔

        -[Contractor Onboarding PDF Updated Macbooks 2025.pdf](https://github.com/user-attachments/files/20515451/Contractor.Onboarding.PDF.Updated.Macbooks.2025.pdf)


        _This access cannot be granted until the Entitlement work below is completed_

        ### WORKPLACE: 
        | | |
        | ---------------------------------- | ---------------------------------- |
        | __Permanent desk needed in office?__| <ul><li>- [ ] Yes</li><li> [ ] No </li>( If yes, IT to cc @ seeglenn)
        | __Access badge for HQ access?__| <ul><li>- [ ] Yes</li><li> [ ] No </li>( If yes, IT to cc @ avrileklund)

        ---
        ### ON-BOARDING:
        #### Hiring Manager is responsible for:
        | | |
        | ---------------------------------- | ---------------------------------- |
        | __Pull Requests__| 1. If your contractor will need access to **ANY** repo's within the overall GitHub organization, they will need to be provisioned through Entitlements. You can do this by opening a Pull Request on this file to add the contractor to github.com/github: https://github.com/github/entitlements/blob/master/github.com/github/org/always-on/member.txt. For more info & assistance please refer to [this document](https://thehub.github.com/it/references/contractor-onboarding/). If they will need access to a team in the org, open a pull request on the appropriate file here: https://github.com/github/entitlements/tree/master/github.com/github/teams   💡 See [documentation](https://github.com/github/entitlements/blob/master/docs/contractors.md#example-using-pizza-teams-to-manage-contractor-access-to-githubcom-and-github-team-assignment) on how to simplify this process if you expect to frequently onboard contractors into your organization. For engineering contractors, please read through [this document](https://github.com/github/contractors/blob/master/engineering-contractors.md) to make sure you are adding them to all the required entitlements. 
        | __Signing In__| 2. Ask the contractor to head to [GitHub](https://www.github.com/settings/security) to set up their 2FA, [accept their invite](https://www.github.com/github), then log in to Okta, and follow the steps in [this document](https://github.com/github/thehub/files/5858652/What.is.WebAuthn.pdf) to set up their 2FA in Okta. **All Contractors MUST have a Yubikey or compatible strong auth factor on their start date. Contractors without a strong auth factor will be unable to log in to Okta.**
        | __Internal Access__| All contractors requiring access to ANY GitHub internal systems or GitHub services must use a GitHub-managed machine. These machines are equipped with special certificates essential for accessing key services like Heaven, Sentry, DataDog, and Splunk, ensuring that only authorized GitHub personnel can access these applications. **Note: A GitHub-managed machine is not required if only Slack Connect access is needed. However, Slack Guest accounts do require a GitHub-managed machine since Okta access is necessary.**
        | __Laptop__| Please open a [Zendesk IT ticket](https://github-it.zendesk.com/hc/en-us/requests/new) with the contractor's shipping address, email and phone number once their account has been onboarded and enabled. (**Note**: IT does not ship laptops to users without active accounts. Additionally, ensure the shipping destination is supported by referring to this [country logistics list](https://github.com/github/Workplace-Security/blob/master/Safety-and-Security-Playbook/Travel-Security-and-Protective-Services/travel-security-country-list.md), as some locations may have country-specific constraints.
        | __Maintaining an Accurate Contract End Date__| The contractor **will lose access** at 12:00pm PT on the end date listed unless a [Contractor Renewal/Offboarding issue](https://github.com/github/procurement/issues/new?assignees=&labels=pre-contract+security-grc+review+NOT+required&template=contractor-renewal-off-boarding-issue.md&title=) is completed prior to the end date. As a manager, you will receive Workday notices 28 days, 14 days and 7 days prior to the contractor's termination date reminding you to take action. You **MUST** create a [Contractor Renewal/Offboarding issue](https://github.com/github/procurement/issues/new?assignees=&labels=pre-contract+security-grc+review+NOT+required&template=contractor-renewal-off-boarding-issue.md&title=) to either a) confirm an offboarding date or b) extend the end date. If your contractor needs to be termed before the end date listed, you must also create a [Contractor Renewal/Offboarding issue](https://github.com/github/procurement/issues/new?assignees=&labels=pre-contract+security-grc+review+NOT+required&template=contractor-renewal-off-boarding-issue.md&title=) right away.
